image: microsoft/dotnet:latest

stages:
  - build

before_script:
  - "dotnet restore -s https://api.nuget.org/v3/index.json"  
  
build:
  stage: build
  script:
    - "cd Moneteer.Identity"
    - "dotnet build --no-restore"