version: "3"
services:
  app:
    build:
      context: app/Moneteer.Identity
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  proxy:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"