version: "3"
services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  proxy:
    build:
      context: nginx/dev
      dockerfile: Dockerfile
    ports:
      - "80:80"