version: "3"
services:
  app:
    image: "525140287988.dkr.ecr.eu-west-1.amazonaws.com/moneteer/identity/app:latest"
    ports:
      - "5000:5000"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "moneteer-identity"
        awslogs-stream-prefix: "app"
  proxy:
    image: "525140287988.dkr.ecr.eu-west-1.amazonaws.com/moneteer/identity/proxy:latest"
    ports:
      - "80:80"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "eu-west-1"
        awslogs-group: "moneteer-identity"
        awslogs-stream-prefix: "proxy"

# Create the service using the default cluster profile
# ecs-cli compose -f docker-compose-identity-aws-production.yml service up --target-group-arn arn:aws:elasticloadbalancing:eu-west-1:525140287988:targetgroup/ecs-moneteer-identity-service/18489a5836104311 --container-name proxy --container-port 80

# Force a new deployment. Used when the service definition doesn't change but you want to update the image
# aws ecs update-service --cluster moneteer-cluster --service moneteer-identity --force-new-deployment